# kudos to https://olegk.dev/github-actions-and-go
name: Build and Qualify

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
  # schedule:
  #   - cron: '0 23 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # strategy:
    #   matrix:
    #     go: ['stable', 'oldstable']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        # go-version: ${{ matrix.go }}
        check-latest: true
        go-version: '^1.20'

    - name: Go Fmt
      run: gofmt -s -w . && git diff --exit-code

    - name: Go Vet
      run: go vet ./...

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      # allows to catch supply chain attacks
      run: go mod verify

    - name: Go Generate
      run: go generate ./... && git diff --exit-code

    - name: Build
      # no need to build a real binary, we don't publish it as an artifact
      # here we want to check if the code can be compiled
      run: go build -o /dev/null  -v ./...
    
    - name: Run Unit Tests
      if: ${{ !inputs.skipTests }}
      run: go test -v -shuffle=on ./...
